/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        outline: '#7a7484',
        error: '#ba1a1a',
        'on-primary': '#ffffff',
        secondary: '#7443ba',
        'on-background': '#1a1c1c',
        'on-primary-fixed': '#23005c',
        'surface-container-low': '#f4f3f3',
        'surface-tint': '#6b47bb',
        'on-secondary-fixed': '#280056',
        'surface-bright': '#f9f9f9',
        'tertiary-fixed': '#f0e67c',
        'on-tertiary-fixed-variant': '#4d4800',
        'surface-container-high': '#e8e8e8',
        'on-secondary-container': '#46038c',
        tertiary: '#676000',
        'on-error-container': '#93000a',
        'surface-container': '#eeeeee',
        'on-surface-variant': '#494452',
        'outline-variant': '#cbc3d4',
        surface: '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        background: '#f9f9f9',
        primary: '#260061',
        'inverse-surface': '#2f3131',
        'primary-fixed': '#e9ddff',
        'primary-container': '#3e0f8d',
        'secondary-fixed-dim': '#d7baff',
        'surface-variant': '#e2e2e2',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#5b27a1',
        'tertiary-fixed-dim': '#d3c963',
        'inverse-primary': '#d0bcff',
        'secondary-fixed': '#eddcff',
        'on-tertiary-fixed': '#1f1c00',
        'on-primary-container': '#aa86fe',
        'secondary-container': '#b482fd',
        'surface-dim': '#dadada',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-primary-fixed-variant': '#522ca1',
        'tertiary-container': '#b7ae4b',
        'on-tertiary-container': '#454100',
        'inverse-on-surface': '#f1f1f1',
        'primary-fixed-dim': '#d0bcff',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'caption-xs': ['11px', { lineHeight: '16px', letterSpacing: '0.4px' }],
        'label-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.3px' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.2px' }],
        'body-sm': ['13px', { lineHeight: '18px' }],
        'body-md': ['15px', { lineHeight: '22px' }],
        'body-lg': ['17px', { lineHeight: '26px' }],
        'title-md': ['17px', { lineHeight: '24px' }],
        'headline-lg': ['20px', { lineHeight: '28px' }],
        'headline-xl': ['28px', { lineHeight: '36px' }],
        'display-lg': ['44px', { lineHeight: '52px' }],
        'data-mono': ['13px', { lineHeight: '18px', fontFamily: 'ui-monospace, SFMono-Regular, monospace' }],
      },
      spacing: {
        'space-3xs': '2px',
        'space-2xs': '4px',
        'space-xs': '8px',
        'space-sm': '12px',
        'space-md': '16px',
        'space-lg': '24px',
        'space-xl': '32px',
        'space-2xl': '48px',
        'space-3xl': '80px',
        'margin-mobile': '20px',
        'margin-tablet': '40px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        '1680': '1680px',
      },
    },
  },
  plugins: [],
}