const LOGO = 'https://lh3.googleusercontent.com/aida/AEtjO1XYLtNk5iMxyiEa4Dpp9oHFjtA_WQX01dZIiBUeudsf4MGVNywUKzA8K5gQJ-V9UncnhudnbY8J5E-byLbC4T9CdHOExckb73nKwzkYOFsDOExhsGjXyt5xc5cFd6BV8ESfCDfXHvS23L-fBdrmqOE9KYFSY7D8o_EMo1oIu46_NWsqMsd5dVfRuD6CAr2NcpV3P-z-Z2jLkV1jTkvWslV_yRjY6uv-Ez4D3uPjTFtoFRnqicjOAERmuhY';

const CARS = [
  {
    key: 'innova-zenix',
    name: 'Toyota Innova Zenix Hybrid',
    cat: 'mpv',
    catLabel: 'Family MPV',
    badge: 'Tahun 2024',
    badge2: { text: 'Tersedia', color: 'bg-secondary text-on-secondary' },
    cornerBadge: { icon: 'eco', label: 'Hybrid', color: 'text-tertiary' },
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCI3VFH2WPEzzN20kTwW5EcUiCysyafzxqrTxpGRR8X3cx8vHjd0CGi_2jEWbrD6YvXQBUQXiuOgbZOcnzSqwbhZEXteeGjMjYWVPPSHwt1HGOh7FeZ62emYTMIap3E7sxbpMOqEORAEcA9v-DiTHBEGzJDXkwgx4btJOceHzPi4r7IWVyZBlCy59Fatp4J7Pha8u1fQz_kfMsBkCXEJvintzr58AE5PLWrC1BseBS78yYEQJUhpgau',
    desc: 'Kabin senyap, suspensi empuk, bahan bakar super hemat 1:21 km/L.',
    rating: '4.9',
    reviews: '128',
    specs: [
      { icon: 'airline_seat_recline_extra', label: '7 Kursi' },
      { icon: 'luggage', label: '3 Koper' },
      { icon: 'settings_suggest', label: 'Matic CVT' },
      { icon: 'local_gas_station', label: 'Hybrid' },
    ],
    price: '650000',
    priceLabel: 'Lepas Kunci:',
    priceUnit: '/ hari',
    extra: '+ Rp 200rb/hari (Sopir)',
  },
  {
    key: 'fortuner-gr',
    name: 'Toyota Fortuner GR Sport 2.8',
    cat: 'suv',
    catLabel: 'Premium SUV',
    badge: 'Tahun 2024',
    badge2: { text: 'Terlaris', color: 'bg-tertiary-fixed text-on-tertiary-fixed' },
    cornerBadge: { icon: 'terrain', label: '4x4 Power', color: 'text-secondary' },
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjjmT7gJn0tfJPY-LPmeXwXvzAqlIRdwLAP9i1iGksoE9wgVSta8MytJnPC7TMngRkPMPZsUzcxpSIS1ICovBd7wCvAq-bmeJRtXSgny0mMurtukyGZ3PlvAwHaIFdxeh_d47WuEOu5yttvmdNWvbeeVmwgvjyON7CGte35wyPwmceuvC2FhR1i3M9RRYk1mQt7VJlckGrto4kIwEKoWydlWqEn3AYIjSCj6K-IXNHMqaAo9itqSPq',
    desc: 'Tangguh untuk luar kota, proyek bisnis, maupun rute berbukit.',
    rating: '4.95',
    reviews: '94',
    specs: [
      { icon: 'airline_seat_recline_extra', label: '7 Kursi' },
      { icon: 'luggage', label: '4 Koper' },
      { icon: 'settings_suggest', label: 'Automatic' },
      { icon: 'local_gas_station', label: 'Diesel' },
    ],
    price: '1100000',
    priceLabel: 'Mulai dari:',
    priceUnit: '/ hari',
    extra: 'Lepas Kunci / Driver',
  },
  {
    key: 'alphard-vip',
    name: 'Toyota Alphard 2.5G Luxury',
    cat: 'vip',
    catLabel: 'Luxury VIP',
    badge: 'Executive VIP',
    badge2: { text: 'With Driver', color: 'bg-surface-container-lowest/90 backdrop-blur-md text-primary' },
    cornerBadge: { icon: 'wifi', label: 'Free Wi-Fi', color: 'text-primary-container' },
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDfoUim-JJWQ3KjWS3mRfSvssc2Qp6Y6LmYhUi4_NE6VmWyCpTAHlNwRF_Mj2ecaTiY6j4_GM33HxPev59m24BheM7MDE2jYy6VpxtTIW2lxKENjUpmMZXk2Z_SaMBMFOrzNfvsA1D4mulDvXipfpXWeNA1zFYj2WSKv_mT62Fx8TR_tEXzQc8rvNow8iQKb016_hBOYo-GhJ74hZS9BjnMmKuPVehJJPALrhwwYfIVjddogV2ZjUuO',
    desc: '6 Captain Seat, Ottoman footrest, mineral water & supir bersetelan jas.',
    rating: '5.0',
    reviews: '210',
    specs: [
      { icon: 'airline_seat_individual_suite', label: '6 Captain' },
      { icon: 'luggage', label: '4 Koper' },
      { icon: 'badge', label: 'Supir VIP' },
      { icon: 'water_drop', label: 'Amenities' },
    ],
    price: '2400000',
    priceLabel: 'Paket All-In Supir:',
    priceUnit: '/ 12 jam',
    extra: 'BBM & Tol optional',
  },
  {
    key: 'ioniq-ev',
    name: 'Hyundai Ioniq 5 Long Range',
    cat: 'ev',
    catLabel: 'City Car / EV',
    badge: 'Eco-Friendly',
    badge2: { text: '100% Listrik', color: 'bg-surface-container-lowest/90 backdrop-blur-md text-primary' },
    cornerBadge: { icon: 'ev_station', label: '450 km Range', color: 'text-secondary' },
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkxYRY9fqiQIv9TeWKZhuV6QChIzKNostr7Ld728LCAN90__XAGlP9D9SF69zSN5aEsNsM5YtFUDrlCG3aVP453H5gtanlDDocl2n10QxULOOc4H97YsEzVWLSykfCZyNk8eAnEobI-guwMZTZqq1EYk9OxNl7vsjDaiv9gEA4rlWHZUUGZDnc1dSXmPHDa50wObY-H2tYvm9ocF_LDa48zmsK6kjmJJ4cp-p2eP9nE8cQ3Fiu9mEB',
    desc: 'Bebas aturan Ganjil-Genap Jakarta, V2L portable power, akselerasi instan.',
    rating: '4.92',
    reviews: '76',
    specs: [
      { icon: 'airline_seat_recline_extra', label: '5 Kursi' },
      { icon: 'luggage', label: '3 Koper' },
      { icon: 'electric_car', label: 'Electric' },
      { icon: 'traffic', label: 'Bebas GaGe' },
    ],
    price: '950000',
    priceLabel: 'Lepas Kunci:',
    priceUnit: '/ hari',
    extra: 'Free Charge Card',
  },
];

export default CARS;

export const Logo = ({ className = 'h-8 w-auto' }) => (
  <img alt="Velocis Fleet Logo" className={className} src={LOGO} />
);